"""empty message

Revision ID: ea071363885a
Revises: 
Create Date: 2020-07-22 15:18:43.899881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea071363885a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('pId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('pName', sa.String(length=100), nullable=False),
    sa.Column('Position', sa.String(length=100), nullable=True),
    sa.Column('Height', sa.String(length=100), nullable=True),
    sa.Column('Weight', sa.String(length=100), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pId')
    )
    op.create_table('statistic',
    sa.Column('statID', sa.Integer(), nullable=False),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('playerTeam', sa.String(length=100), nullable=False),
    sa.Column('oppositionTeam', sa.String(length=100), nullable=False),
    sa.Column('dribbleSuc', sa.Integer(), nullable=False),
    sa.Column('dribbleUnSuc', sa.Integer(), nullable=False),
    sa.Column('passCompleted', sa.Integer(), nullable=False),
    sa.Column('passUnCompleted', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('chancesCreated', sa.Integer(), nullable=False),
    sa.Column('goalsScored', sa.Integer(), nullable=False),
    sa.Column('shotsOnTarget', sa.Integer(), nullable=False),
    sa.Column('shotsOffTarget', sa.Integer(), nullable=False),
    sa.Column('clearances', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('tacklesSuc', sa.Integer(), nullable=False),
    sa.Column('foulsSuffered', sa.Integer(), nullable=False),
    sa.Column('foulsCommitted', sa.Integer(), nullable=False),
    sa.Column('yellowCard', sa.Integer(), nullable=False),
    sa.Column('redCard', sa.Integer(), nullable=False),
    sa.Column('minutesPlayed', sa.Integer(), nullable=False),
    sa.Column('statDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['playerId'], ['player.pId'], ),
    sa.PrimaryKeyConstraint('statID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('player')
    op.drop_table('users')
    # ### end Alembic commands ###
